EMS/EMS/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('events.urls')),
    # path('', include('blog.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),

    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('pages/', include(wagtail_urls)),
    # path('', include('allauth.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

EMS/events/urls.py
from django.urls import path, include
from events import views

app_name = 'events'
urlpatterns = [
   # path('', views.login_view, name='login'),
   path('', include('users.urls')),
   path('home/', views.IndexView.as_view(), name='index'),
   path('locations/', views.LocationView.as_view(), name='locations'),
   path('events/', views.EventView.as_view(), name='events'),
   path('locations/<pk>/locations_details/', views.location_detail, name='locations_details'),
   path('events/<pk>/events_details/', views.event_detail, name='events_details'),
   path('event/add/', views.EventCreate.as_view(), name='event-add'),
   path('event/<pk>/update', views.EventUpdate.as_view(), name='event-update'),
   path('location/add', views.LocationCreate.as_view(), name='locations-add'),
   path('events/drafted_events/', views.DraftEventView.as_view(), name='drafted-events'),
   path('events/published_events/', views.PublishedEventView.as_view(), name='published_events'),
   path('events/withdrawn_events/', views.WithdrawnLocationView.as_view(), name='withdrawn_location'),
   path('locations/drafted_locations/', views.DraftLocationView.as_view(), name='drafted_locations'),
   path('locations/published_locations/', views.PublishLocationView.as_view(), name='published_locations'),
   path('locations/withdrawn_locations/', views.WithdrawnLocationView.as_view(), name='withdrawn_locations'),
   path('search_results/', views.SearchResultsView.as_view(), name='search_results'),
   # path('locations/<pk>/publish/', views.location_publish, name='location_publish'),
]

EMS/users/urls.py
from django.urls import path, include
from users import views

app_name = 'users'
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls')),
    path('register/', views.register, name="register"),
]

EMS/events/forms.py
from django import forms
from events.models import Event, Location
from django.utils.html import format_html, escape, mark_safe
from string import Template


class PictureWidget(forms.widgets.Widget):
    def render(self, name, value, attrs=None, **kwargs):
        html =  Template("""<img src="$link"/>""")
        return mark_safe(html.substitute(link=value))


class EventForm(forms.ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    # Image = forms.ImageField(widget=PictureWidget)

    class Meta:
        model = Event
        fields = ('name', 'details','description_ar', 'date', 'time', 'image',)
        # widgets = {
        #     'image' : forms.ImageField({'is_hidden' : False})
        # }


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ('name', 'event_location', 'image', )

EMS/events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from .models import Location, Event, EventImage, LocationImage, DraftEvent, PublishedEvent, WithdrawnEvent, \
    DraftLocation, PublishedLocation, WithdrawnLocation
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from events.forms import EventForm, LocationForm
from itertools import chain
from django.urls import reverse_lazy
from django.db.models import Q


# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth import login
# Create your views here.


class EventView(generic.ListView):
    template_name = 'events.html'
    context_object_name = 'events_list'

    def get_queryset(self):
        return Event.objects.order_by('date')[:5]


class DraftEventView(generic.ListView):
    template_name = 'draft_events.html'
    context_object_name = 'draft_events'

    def get_queryset(self):
        return DraftEvent.objects.all()


class WithdrawnEventView(generic.ListView):
    template_name = 'withdrawn_events.html'
    context_object_name = 'withdrawn_events'

    def get_queryset(self):
        return WithdrawnEvent.objects.all()


class PublishedEventView(generic.ListView):
    template_name = 'published_events.html'
    context_object_name = 'published_events'

    def get_queryset(self):
        return PublishedEvent.objects.all()


class LocationView(generic.ListView):
    template_name = 'locations.html'
    context_object_name = 'locations_list'

    def get_queryset(self):
        return Location.objects.all()[:5]


class DraftLocationView(generic.ListView):
    template_name = 'drafted_locations.html'
    context_object_name = 'drafted_locations'

    def get_queryset(self):
        return DraftLocation.objects.all()


class PublishLocationView(generic.ListView):
    template_name = 'published_locations.html'
    context_object_name = 'published_locations'

    def get_queryset(self):
        return PublishedLocation.objects.all()


class WithdrawnLocationView(generic.ListView):
    template_name = 'withdrawn_locations.html'
    context_object_name = 'withdrawn_locations'

    def get_queryset(self):
        return WithdrawnLocation.objects.all()


class IndexView(generic.ListView):
    template_name = 'base.html'
    context_object_name = 'locations_list'

    def get_queryset(self):
        return Location.objects.all()


class EventCreate(CreateView):
    # model = Event
    # fields = ('name', 'event_details', 'date', 'time', 'image', )
    template_name = "events/event_form.html"
    context_object_name = 'event'
    success_message = "%(name)s was created successfully"

    form_class = EventForm

    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.image = self.request.FILES['image']
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('events:events'))
        else:
            render(self.request, 'events/event_form.html', {'form': form})

    # def get(self, request, *args, **kwargs):
    #     context = {'form': EventForm()}
    #     return render(request, 'events/event_form.html', context)
    #
    # def post(self, request, *args, **kwargs):
    #     form = EventForm(request.POST, request.FILES)
    #     if form.is_valid():
    #         form.save()
    #         return HttpResponseRedirect(reverse_lazy('events:events'))
    #     return render(request, 'events/event_form.html', {'form': form})


class EventUpdate(UpdateView):
    model = Event
    fields = ('name', 'details', 'date', 'time', 'creator','description')
    template_name = "events/event_form.html"
    context_object_name = 'event'

    def form_valid(self, form):
        form.instance.creator = self.request.user
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('events:events'))
        else:
            render(self.request, 'events/event_form.html', {'form': form})

    # def get(self, request, *args, **kwargs):
    #     context = {'form': EventForm()}
    #     return render(request, 'events/event_form.html', context)
    #
    # def post(self, request, *args, **kwargs):
    #     form = EventForm(request.POST)
    #     if form.is_valid():
    #         event = form.save()
    #         return HttpResponseRedirect(reverse_lazy('events:events'))
    #     return render(request, 'events/event_form.html', {'form' : form})


class LocationCreate(CreateView):
    model = Location
    form_class = LocationForm
    template_name = "events/location_form.html"
    context_object_name = 'location'

    def get(self, request, *args, **kwargs):
        context = {'form': LocationForm()}
        return render(request, 'events/location_form.html', context)


def location_detail(request, pk):
    location = Location.objects.get(pk=pk)
    return render(request, 'locations_details.html', {'location': location})


def event_detail(request, pk):
    event = Event.objects.get(pk=pk)
    return render(request, 'events : events_details', event)


class EventView(generic.ListView):
    template_name = 'events.html'
    context_object_name = 'events_list'

    def get_queryset(self):
        return Event.objects.order_by('date')[:5]

# @user_passes_test(lambda user: user.is_superuser)
# @login_required
# # @permission_required('events.')
# def location_publish(request, pk):
#     # is_superuser = request.user.is_superuser
#     # if not is_superuser:
#     #     return
#     location = get_object_or_404(Location, pk=pk)
#     location.publish()
#     location_publish.allowed_permissions = ('publish', )
#     return redirect('/locations/')


class SearchResultsView(generic.ListView):
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        event_objects = Event.objects.filter(
            Q(name__icontains=query)
        )
        location_objects = Location.objects.filter(
            Q(name__icontains=query)
        )
        return event_objects, location_objects

EMS/events/templates/events/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <meta charset="UTF-8">
    <title>Event Management System</title>
</head>
<body>
       <div class="navbar">
           <ul>
                <li>
               <a href="{% url 'events:index' %}"><h1>EMS</h1></a>
                </li>
                <li>
                    <a href="{% url 'events:locations' %}">Explore<span>(current)</span></a>
                </li>
                <li>
                    <a href="{% url 'events:event-add' %}">Create a new Event</a>
                </li>
                <form method="get" action="{% url 'events:search_results' %}">
                <input name="q" type="search" placeholder="Search" aria-label="Search">
                <button type="submit">Search</button>
                </form>
                      <p class="button-register"><a href="{% url 'users:register' %}">Register</a></p>
           </ul>
       </div>
       <div class="locations">
           {% for location in locations_list %}
           <p>    {{ location.name}} {{location.events_names }} </p>
           {% endfor %}
       </div>

{% block content %}
{% endblock content %}
</body>
</html>

EMS/events/templates/events/draft_events.html
{% extends 'events/base.html' %}
{% block content %}
{% for event in draft_events %}
<p>{{ event.name }}</p>
<img src="{{ event.image.url }}" width="700" height="500">
{% endfor %}
{% endblock %}

EMS/events/templates/events/drafted_locations.html
{% extends 'events/base.html' %}
{% block content %}
{% for location in drafted_locations %}
<p>{{ location }}</p>
<img src="{{ location.image.url }}" width="700" height="500">
{% endfor %}
{% endblock %}

EMS/events/templates/events/event_confirm_delete.html
{% extends "events/base.html" %}
{% block content %}
<form action="" method="post">
    {% csrf token %}
    {{
</form>

EMS/events/templates/events/event_form.html
{% extends 'events/base.html' %}
{% load static %}
{% block content %}
 {{ form.media }}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <img src="{{ form.image.url }}" width="150" height="200">
    <input type="submit" value="Save" >
</form>
{% endblock %}

EMS/events/templates/events/events.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1> {% trans "HOME PAGE" %} </h1>
<ul>
    {% for event in events_list %}
    <li style="color:white;">
    {{ event.name }}--{{ event.date }}
        {{ event.description }}
        {% if request.user.is_authenticated and request.user == event.creator %}
                <p><a href="{% url 'events:event-update' pk=event.pk %}" style="color:white;">Update</a></p>
        {% endif %}
        </li>
    {% endfor %}
</ul>
{% endblock content %}

EMS/events/templates/events/location_form.html
{% extends 'events/base.html' %}
{% block content %}
 {{ form.media }}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" >
</form>
{% endblock %}

EMS/events/templates/events/locations.html
{% extends 'base.html' %}
{% block content %}
<!--{% load static %}-->

<ul>
{% for location in locations_list %}
    <li>
        <h1><a href="{% url 'events:locations_details' pk=location.pk %}" style="color:white;">{{ location.name}}</a></h1>


    </li>
<!--    <span style="color: #00FF00;">{{ location.status }}</span>-->
    {% endfor %}
</ul>

{% endblock content %}

EMS/events/templates/events/locations_details.html
{% extends 'base.html' %}
{% block content %}
<h1><a href="https://www.google.com.tr/maps/">{{location.location_name}}</a></h1>

<p>{{location.events_names}}</p>

{% endblock content %}

EMS/events/templates/events/published_events.html
{% extends 'events/base.html' %}
{% block content %}
{% for event in published_events %}
<p>{{ event }} </p>
<img src="{{ event.image.url }}" width="700" height="500">
{% endfor %}
{% endblock %}

EMS/events/templates/events/published_locations.html
{% extends 'events/base.html' %}
{% block content %}
{% for location in published_locations %}
<p>{{ location }}</p>
<img src="{{ location.image.url }}" width="700" height="500">
{% endfor %}
{% endblock %}

EMS/events/templates/events/search_results.html
{% extends 'events/base.html' %}
{% block content %}
{% for event in event_objects %}
<p>{{ event }}</p>
{% endfor %}
{% for location in location_objects %}
<p>{{ location }}</p>
{% endfor %}
{% endblock %}

EMS/events/templates/events/withdrawn_locations.html
{% extends 'events/base.html' %}
{% block content %}
{% for location in withdrawn_locations %}
<p>{{ location }}</p>
<img src="{{ location.image.url }}" width="700" height="500">
{% endfor %}
{% endblock %}